### ISSUE TITLE
Option to automatically pass transactions to all queries

### ISSUE THREAD

**Issue by kytwb** [actionhero/ah-sequelize-plugin#45]
See http://docs.sequelizejs.com/en/latest/docs/transactions/#automatically-pass-transactions-to-all-queries

**Comment by bayssmekanique** [comment]
@kytwb, I see the advantages here, but I don't think CLS support for `async/await` is quite there.  From my digging it relies on https://github.com/Jeff-Lewis/cls-hooked which uses "experimental" features in Node.

I will look into this a bit more, since I would like this capability as well, but I'm hesitant to make it a project dependency, so if anything this will likely be a config hook.

**Comment by evantahler** [comment]
This is possible within https://sequelize.org/v3/docs/transactions/
